version: '3.3'
services:
  database:
    image: mysql:5.7.30
    restart: always
    container_name: movies-db
    environment:
      MYSQL_DATABASE: movies
      MYSQL_USER: movies
      MYSQL_PASSWORD: movies
      MYSQL_ROOT_PASSWORD: movies
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
