name: Tests

on:
  push:
    branches: '*'

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#      - name: Build test config file
#        run: cp .env.example .env

      - name: Install project depedencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Run project tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test

      - name: Build project
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
