name: Tests

on:
  push:
    branches: '*'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7.12
        ports:
          - 3316:3306
        env:
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test

    steps:
      - uses: actions/checkout@v2

      - name: Build test config file
        run: cp config/test.dist.json config/test.json

      - name: Install project depedencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Run project tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test

      - name: Build project
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
